FROM rust:1.92-slim-bullseye AS BUILDER

WORKDIR widehabit/

COPY . .

RUN --mount=type=cache,target=/var/cache/apt \
    apt update && apt install libpq-dev -y

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/target \
    cargo install diesel_cli --no-default-features --features postgres

ENTRYPOINT ["diesel", "migration", "run"]