FROM rust:1.92-slim-bookworm as BUILDER

WORKDIR widehabit/

RUN rustup target add x86_64-unknown-linux-musl

COPY . .

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/widehabit/target \
    cargo build --target x86_64-unknown-linux-musl --release && \
    cp target/x86_64-unknown-linux-musl/release/widehabit /usr/local/bin/widehabit

FROM alpine:3.23

COPY --from=builder /usr/local/bin/widehabit /usr/local/bin/widehabit

ENTRYPOINT ["widehabit"]